name: quranapps_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.9.2

dependencies: 
  cupertino_icons: ^1.0.8
  get: 4.7.3
  http: 1.6.0
  lottie: 3.3.2
  introduction_screen: 4.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lotties/
  uses-material-design: true

